name: yuva
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  provider: ^6.1.2
  image_picker: ^1.0.7
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  intl: ^0.19.0
  share_plus: ^11.0.0
  flutter_image_compress: ^2.4.0
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^17.1.2
  pin_code_fields: ^8.0.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_screenutil: ^5.9.0
  video_compress: ^3.1.4
  video_player: ^2.10.0
  flutter_cache_manager: ^3.4.1
  video_thumbnail: ^0.5.3
  path_provider: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    
    - assets/ug_courses.json
    - assets/pg_courses.json
    - assets/interests.json
    - assets/colleges.json
    - assets/logo.png
    
    