// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB63sDl65hiKwUD_XV0gw24FMuEapk_SaI',
    appId: '1:1004683858944:web:57966368749201487274e5',
    messagingSenderId: '1004683858944',
    projectId: 'yuva-1263',
    authDomain: 'yuva-1263.firebaseapp.com',
    storageBucket: 'yuva-1263.firebasestorage.app',
    measurementId: 'G-41PNC4KFD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIGRhEK4ZO4HFV37t9iKY1R2g3zVOUDPA',
    appId: '1:1004683858944:android:8f4e193687d965037274e5',
    messagingSenderId: '1004683858944',
    projectId: 'yuva-1263',
    storageBucket: 'yuva-1263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsx4vXg10mvOn52MLf6RQlBErm5IEoEz4',
    appId: '1:1004683858944:ios:5718b2b655bc34237274e5',
    messagingSenderId: '1004683858944',
    projectId: 'yuva-1263',
    storageBucket: 'yuva-1263.firebasestorage.app',
    iosBundleId: 'com.example.yuva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsx4vXg10mvOn52MLf6RQlBErm5IEoEz4',
    appId: '1:1004683858944:ios:5718b2b655bc34237274e5',
    messagingSenderId: '1004683858944',
    projectId: 'yuva-1263',
    storageBucket: 'yuva-1263.firebasestorage.app',
    iosBundleId: 'com.example.yuva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB63sDl65hiKwUD_XV0gw24FMuEapk_SaI',
    appId: '1:1004683858944:web:1ccdca93525205957274e5',
    messagingSenderId: '1004683858944',
    projectId: 'yuva-1263',
    authDomain: 'yuva-1263.firebaseapp.com',
    storageBucket: 'yuva-1263.firebasestorage.app',
    measurementId: 'G-E1JNT432HN',
  );
}
